### ISSUE TITLE
Create and publish chocolatey artifact

### ISSUE THREAD

**Issue by 030** [030/dip#5]

**Comment by 030** [comment]
@digitalcoyote That is great. Will you add a package to your chocolatey-packages repository? Does the windows dip binary work as expected? Please let me know if something has to be adjusted in order to make it work.

**Comment by digitalcoyote** [comment]
@030 My goal is generally to require no changes from the project maintainers. I will add it to my 
 AU repo to keep it up to date. if you create a Chocolatey account, I can add you as a maintainer (gives basic management rights such as delisting problematic versions).

I'll try to get a package up during lunch today.

**Comment by 030** [comment]
@digitalcoyote Thanks for creating a package. I hope to create an account in the upcoming weekend. If there are any other tools you would like to package, please let me know.

**Comment by 030** [comment]
@digitalcoyote Thanks again for creating the package. At the moment I do not have a Windows system. Thanks for the offer to add me as a maintainer.

**Comment by 030** [comment]
@digitalcoyote 1.3.5 is available. I have revived my user account, utrecht. Could you add me as a maintainer? Where to find the chocolatey package? Did you create a github repository?

**Comment by digitalcoyote** [comment]
[Chocolatey](https://chocolatey.org/packages/dip) should have the latest version pushed shortly (my CI checks twice daily for new packages to build/push)
[Package Source](https://github.com/digitalcoyote/chocolatey-packages/tree/master/dip) is part of my AU repo (includes the CI scripts that automatically update it)
