### ISSUE TITLE
get latest images from gitlab, harbor, redhat, jfrog, quay

### ISSUE THREAD

**Issue by 030** [030/dip#56]
ghcr.io
mcr.microsoft.com
k8s.gcr.io

* registry.access.redhat.com/ubi8/ubi-minimal:latest. Example: https://catalog.redhat.com/software/containers/rh-sso-7/sso74-openshift-rhel8/5e7e033d5a1346687697bbd3
* quay.io/jetstack/cert-manager-controller:v1.1.0
  * https://docs.quay.io/api/swagger/ 
* registry.gitlab.com/<some-org>/image-name
* https://docker.bintray.io/ui. Example: https://docker.bintray.io/ui/packages/docker:%2F%2Fjfrog%2Fartifactory-oss?name=jfrog%2Fartifactory-oss&type=packages

**Comment by Akaame** [comment]
Hello,

I am not sure how to approach this problem, so having a brain dump here. I see that currently we have one docker registry ( default docker registry ) and I expect every other registry to comply with the same HTTP/REST API. For images that does not have a Registry URL section, we can extend the list by having a list of publicly available docker registries and just iterate over them until we hit the image. For the ones that do have the URL we want to target that endpoint anyway.

However private repositories like internal harbor, GCR, GHCR need some sort of authentication. So you also need to copy the behavior of `RegistryLogin` in the `docker/client`. 

Actions Items:
* I want to confirm that other registries (public and private) conform to the same REST api as standard docker registry does.

Cheers!

**Comment by Akaame** [comment]
Findings: 

Sorry I confused the links.

`https://hub.docker.com/v2/repositories/` is not Docker Official Registry link. It is the Docker Hub link. Official docker registry link which is also hard coded into moby project is `https://registry-1.docker.io/`. The Registry API is the standard that every registry service should implement. Moving forward with this info:

[Listing repositories section](https://docs.docker.com/registry/spec/api/#listing-repositories) in the API documentation says `v2/_catalog` is the endpoint to list the repositories in the registry.

https://registry-1.docker.io/v2/_catalog fails with unauthorized.

https://registry.access.redhat.com/v2/_catalog fails with not found

Weirdly https://registry.access.redhat.com/v2 redirects me to https://crane.rhcc-registry.svc:8443/v2/ (probably this project https://github.com/pulp/crane)

I do not think any registry provider out there implements the [Hub API spec](https://docs.docker.com/docker-hub/api/latest/). So implementing docker registry client or at least falling back on `docker/client` library (which needs a working docker host to function) is important for future.

Please consider setting up "discussions" on github as to facilitate further discussions on such subjects.

Cheers.

**Comment by 030** [comment]
@Akaame Good idea. I just created [one](https://github.com/030/dip/discussions/86).
